apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: chatcal-ai
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/execution-environment: gen2
spec:
  template:
    metadata:
      annotations:
        # Cost optimization settings
        autoscaling.knative.dev/minScale: "0"  # Scale to zero when idle
        autoscaling.knative.dev/maxScale: "10" # Limit max instances
        run.googleapis.com/cpu-throttling: "true"  # Throttle CPU when idle
        run.googleapis.com/memory: "512Mi"     # Minimum memory for cost efficiency
        run.googleapis.com/cpu: "1000m"        # 1 vCPU
    spec:
      serviceAccountName: chatcal-runner@chatcal-ai-prod-monroe919.iam.gserviceaccount.com
      containerConcurrency: 100  # Handle multiple requests per instance
      timeoutSeconds: 300        # 5 minute timeout
      containers:
      - image: gcr.io/chatcal-ai-prod-monroe919/chatcal-ai:latest
        ports:
        - containerPort: 8080
        env:
        # Non-sensitive environment variables
        - name: ENVIRONMENT
          value: "production"
        - name: TESTING_MODE
          value: "false"
        - name: GOOGLE_CLIENT_ID
          value: "432729289953-1di05ajntobgvv0aakgjahnrtp60491j.apps.googleusercontent.com"  # Not sensitive
        - name: SMTP_SERVER
          value: "smtp.gmail.com"
        - name: SMTP_PORT
          value: "587"
        - name: SMTP_USERNAME
          value: "your-email@gmail.com"
        - name: MY_EMAIL_ADDRESS
          value: "pgits.job@gmail.com"
        - name: MY_PHONE_NUMBER
          value: "555-123-4567"
        # Sensitive variables from Secret Manager
        - name: GROQ_API_KEY
          valueFrom:
            secretKeyRef:
              name: groq-api-key
              key: latest
        - name: SMTP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: smtp-password
              key: latest
        - name: GOOGLE_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: google-client-secret
              key: latest
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: secret-key
              key: latest
        resources:
          limits:
            memory: "512Mi"
            cpu: "1000m"
          requests:
            memory: "256Mi"
            cpu: "100m"  # Minimal CPU request for cost efficiency