version: '3.8'

services:
  api:
    build: .
    container_name: chatcal-api
    ports:
      - "8000:8000"
    environment:
      - APP_ENV=production
      - REDIS_URL=redis://redis:6379/0
    env_file:
      - .env
    depends_on:
      - redis
    volumes:
      - ./credentials:/app/credentials
    restart: unless-stopped
    networks:
      - chatcal-network

  redis:
    image: redis:7-alpine
    container_name: chatcal-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped
    networks:
      - chatcal-network

# nginx:
  #   image: nginx:alpine
  #   container_name: chatcal-nginx
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
  #     - ./docker/nginx/ssl:/etc/nginx/ssl:ro
  #     - ./frontend/dist:/usr/share/nginx/html:ro
  #   depends_on:
  #     - api
  #   restart: unless-stopped
  #   networks:
  #     - chatcal-network

volumes:
  redis-data:

networks:
  chatcal-network:
    driver: bridge